apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    # URL du serveur ACME pour Let's Encrypt en production
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email à utiliser pour les notifications de renouvellement et la récupération des comptes perdus
    email: corentindevpro@hotmail.com
    # Nom du secret qui contiendra la clé privée du compte ACME
    privateKeySecretRef:
      name: letsencrypt-production
    # Configuration de la méthode de validation du domaine
    solvers:
      - http01:
          ingress:
            class: nginx